{% raw -%}
name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
{%- endraw %}
{%- set year | int %}{% now 'local', '%Y' %}{% endset %}{% set maxpython = year - 2011 %}
{%- set minpython = cookiecutter.requires_python.split('.')[1] | int %}
{%- if minpython < 8 %}
        os: [ubuntu-18.04, macos-latest, windows-latest]
{%- else %}
        os: [ubuntu-latest, macos-latest, windows-latest]
{%- endif %}
        python-version:
{%- if minpython < maxpython - 1 %}
{%- for v in range(minpython, maxpython) %}
          - '3.{{ v }}'
{%- endfor %}
{%- if minpython < 5 %}
        exclude:
          - os: macos-latest
            python-version: '3.4'
          - os: windows-latest
            python-version: '3.4'
{%- endif %}
{%- else %}
          - '3.x'
{%- endif %}

{% raw -%}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Python Version
      #   run: python --version
      - name: Install Dependencies
        run: python -m pip install -U --disable-pip-version-check --no-cache-dir pip tox
      - name: Test
{%- endraw %}
        run: tox -e lint,py{% if minpython < maxpython - 1 %},report{% endif %}
{%- raw %}
      - uses: codecov/codecov-action@v2
        with:
          env_vars: OS=${{ matrix.os }},PYTHON=${{ matrix.python-version }}
          files: ./coverage.xml
{%- endraw %}
