repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.3.1
    hooks:
    - id: autoflake
      args:
        - --in-place
        - --recursive
        - --remove-all-unused-imports
        - --expand-star-imports
        - --ignore-init-module-imports
        - --remove-duplicate-keys
        - --remove-unused-variables
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.0
    hooks:
    - id: isort
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
