dist: xenial
language: python

stages:
  - test
  - deploy

install: pip install -U tox
script: tox

{% set number = cookiecutter.requires_python.split('.')[1] | int -%}
jobs:
  include:
{%- for v in range(number, 10) %}
    - python: 3.{{ v }}
      env: TOXENV=py3{{ v }}
{%- endfor %}
    - stage: deploy
      name: "Deploy to PyPI"
      python: 3.9
      install: pip install -U pip build
      script: python -m build
      deploy:
        provider: pypi
        distributions: "sdist bdist_wheel"
        username: __token__
        password: $PYPI_PASSWORD
        edge: true
        skip_existing: true
        on:
          python: 3.9
          tags: true
          branch: main
